/*
 * The embed's one icon, generated the way the panel's are - see
 * src/panel/icons.js for why the markup is inlined. Its own module so the
 * two machines that write embed source cannot fight: biome formats
 * src/embed/index.js, sync-phosphor owns everything between these markers,
 * and this file is excluded from formatting for exactly that reason.
 */
/*
 * Phosphor, inlined - the embed ships as one file into somebody else's page
 * and cannot fetch an icon font. tools/sync-phosphor.mjs copies the markup
 * for what it draws out of @phosphor-icons/core.
 */
// --- phosphor:start (generated by tools/sync-phosphor.mjs) ---
const PHOSPHOR = {
  'map-pin-fill': '<path d="M128,16a88.1,88.1,0,0,0-88,88c0,75.3,80,132.17,83.41,134.55a8,8,0,0,0,9.18,0C136,236.17,216,179.3,216,104A88.1,88.1,0,0,0,128,16Zm0,56a32,32,0,1,1-32,32A32,32,0,0,1,128,72Z"/>',
};
// --- phosphor:end ---
export const icon = (name, cls = 'size-4') =>
  `<svg class="${cls}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">${PHOSPHOR[name] ?? ''}</svg>`;
