/*
 * Copy the shared screen-matching logic into the two browser files.
 *
 * The panel and the embed each ship as one self-contained script down two
 * delivery paths (a <script> tag and an extension import), so neither can
 * import lib/screen-match.js — and three hand-maintained copies of "which
 * screen is this?" is exactly the drift walkdown exists to catch. The module
 * is the source; this pastes it in between markers.
 *
 *   node tools/sync-shared.mjs            # rewrite the blocks
 *   node tools/sync-shared.mjs --check    # fail if they are out of date
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

const HERE = dirname(new URL(import.meta.url).pathname);
const ROOT = join(HERE, '..');
// The panel's source moved under src/ when the bundler arrived; lib/viewer
// is where the built copy lands, and writing generated blocks there would
// be undone by the very next `npm run build:js`.
const TARGETS = [join(ROOT, 'src', 'panel', 'index.js'), join(ROOT, 'lib', 'viewer', 'embed.js')];

/*
 * Each shared block: one source module, one marker name. Both browser files
 * carry every block, so a change to a source lands on both deliveries or the
 * --check run fails the build.
 */
const BLOCKS = [
  { name: 'screen-match', source: join(ROOT, 'lib', 'screen-match.js') },
  { name: 'message-stream', source: join(ROOT, 'lib', 'message-stream.js') },
];
const INDENT = '  ';

const region = (src, file, start, end) => {
  const from = src.indexOf(start);
  const to = src.indexOf(end);
  if (from < 0 || to < 0) {
    console.error(`markers not found in ${file} — add:\n${INDENT}${start}\n${INDENT}${end}`);
    process.exit(1);
  }
  return { from, to };
};

const check = process.argv.includes('--check');
let stale = 0;

for (const block of BLOCKS) {
  const start = `// --- ${block.name}:start ---`;
  const end = `// --- ${block.name}:end ---`;
  const source = readFileSync(block.source, 'utf8');
  const { from: sFrom, to: sTo } = region(source, block.source, start, end);
  const body = source.slice(sFrom + start.length, sTo).replace(/^\n|\n$/g, '');
  const generated = [
    `${INDENT}${start} (generated by tools/sync-shared.mjs — edit ${relative(ROOT, block.source)}) ---`,
    ...body.split('\n').map((line) => (line ? INDENT + line : line)),
    `${INDENT}${end}`,
  ].join('\n');

  for (const target of TARGETS) {
    const src = readFileSync(target, 'utf8');
    const { from, to } = region(src, target, start, end);
    // Cut from the start of the marker's own line so the block replaces cleanly
    // whatever the surrounding indentation happens to be.
    const lineStart = src.lastIndexOf('\n', from) + 1;
    const next = src.slice(0, lineStart) + generated + src.slice(to + end.length);
    if (next === src) continue;
    stale += 1;
    if (!check) writeFileSync(target, next);
    console.log(`${check ? 'stale' : 'synced'}: ${block.name} → ${relative(ROOT, target)}`);
  }
}

if (check && stale) {
  console.error('shared code is out of date — run: node tools/sync-shared.mjs');
  process.exit(1);
}
if (!stale) console.log('shared code up to date');
