/*
 * Copy the shared screen-matching logic into the two browser files.
 *
 * The panel and the embed each ship as one self-contained script down two
 * delivery paths (a <script> tag and an extension import), so neither can
 * import lib/screen-match.js — and three hand-maintained copies of "which
 * screen is this?" is exactly the drift walkdown exists to catch. The module
 * is the source; this pastes it in between markers.
 *
 *   node tools/sync-shared.mjs            # rewrite the blocks
 *   node tools/sync-shared.mjs --check    # fail if they are out of date
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

const HERE = dirname(new URL(import.meta.url).pathname);
const ROOT = join(HERE, '..');
const SOURCE = join(ROOT, 'lib', 'screen-match.js');
const TARGETS = [join(ROOT, 'lib', 'viewer', 'panel.js'), join(ROOT, 'lib', 'viewer', 'embed.js')];

const START = '// --- screen-match:start ---';
const END = '// --- screen-match:end ---';
const INDENT = '  ';

const region = (src, file) => {
  const from = src.indexOf(START);
  const to = src.indexOf(END);
  if (from < 0 || to < 0) {
    console.error(`markers not found in ${file} — add:\n${INDENT}${START}\n${INDENT}${END}`);
    process.exit(1);
  }
  return { from, to };
};

const source = readFileSync(SOURCE, 'utf8');
const { from: sFrom, to: sTo } = region(source, SOURCE);
const body = source.slice(sFrom + START.length, sTo).replace(/^\n|\n$/g, '');
const generated = [
  `${INDENT}${START} (generated by tools/sync-shared.mjs — edit lib/screen-match.js) ---`,
  ...body.split('\n').map((line) => (line ? INDENT + line : line)),
  `${INDENT}${END}`,
].join('\n');

let stale = 0;
for (const target of TARGETS) {
  const src = readFileSync(target, 'utf8');
  const { from, to } = region(src, target);
  // Cut from the start of the marker's own line so the block replaces cleanly
  // whatever the surrounding indentation happens to be.
  const lineStart = src.lastIndexOf('\n', from) + 1;
  const next = src.slice(0, lineStart) + generated + src.slice(to + END.length);
  if (next === src) continue;
  stale += 1;
  if (!process.argv.includes('--check')) writeFileSync(target, next);
  console.log(`${process.argv.includes('--check') ? 'stale' : 'synced'}: ${relative(ROOT, target)}`);
}

if (process.argv.includes('--check') && stale) {
  console.error('shared screen-matching is out of date — run: node tools/sync-shared.mjs');
  process.exit(1);
}
if (!stale) console.log('shared screen-matching up to date');
